{% set name = "mdit-py-plugins" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
    sha256: f4918cb50119f50446560513a8e311d574ff6aaed72606ddae6d35716fe809c6
  - url: https://github.com/executablebooks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f9563423e4e4b4b4e4b6c8372b02cf403bc6adb7a5e1f8268ebab3c494732eda
    folder: gh

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.4,<4
  run:
    - markdown-it-py >=2.0.0,<5.0.0
    - python

# Missing pytest-regressions in main channel
{% set ignore_tests = " --ignore=gh/tests/test_tasklists.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_substitution.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_field_list.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_dollarmath.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_container.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_colon_fence.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_attrs.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_amsmath.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_admon.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_deflist.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gh/tests/test_texmath.py" %}

test:
  source_files:
    - gh/tests
  imports:
    - mdit_py_plugins
    - mdit_py_plugins.admon
    - mdit_py_plugins.amsmath
    - mdit_py_plugins.anchors
    - mdit_py_plugins.attrs
    - mdit_py_plugins.colon_fence
    - mdit_py_plugins.container
    - mdit_py_plugins.deflist
    - mdit_py_plugins.dollarmath
    - mdit_py_plugins.field_list
    - mdit_py_plugins.footnote
    - mdit_py_plugins.front_matter
    - mdit_py_plugins.myst_blocks
    - mdit_py_plugins.myst_role
    - mdit_py_plugins.subscript
    - mdit_py_plugins.substitution
    - mdit_py_plugins.tasklists
    - mdit_py_plugins.texmath
    - mdit_py_plugins.utils
    - mdit_py_plugins.wordcount
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest {{ ignore_tests }} -v gh/tests

about:
  home: https://github.com/executablebooks/mdit-py-plugins
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of plugins for markdown-it-py
  description: Collection of plugins for markdown-it-py
  dev_url: https://github.com/executablebooks/mdit-py-plugins
  doc_url: https://markdown-it-py.readthedocs.io/en/latest/plugins.html

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf